[package]
name = "keycode-gen"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde-hjson = "1.1.0"
regex = "1.12.2"
semver = "1.0.27"
