[workspace]
resolver = "3"
members = ["crates/*", "xtask"]
exclude = ["firmware"]

[workspace.package]
authors = ["storycraft <storycraft@pancake.sh>"]
publish = false
version = "0.1.0"
edition = "2024"
license = "GPL-2.0"
