[workspace]
resolver = "3"
members = ["firmware", "keycodes"]

[profile.release]
lto = true

[workspace.package]
authors = ["storycraft <storycraft@pancake.sh>"]
publish = false
version = "0.1.0"
edition = "2024"
license = "GPL-2.0"
