[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "picotool load --update --verify --execute -t elf"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
# Serial, Via, Gamepad, Mouse, Keyboard, System Control
EMBASSY_USB_MAX_INTERFACE_COUNT = 6
