[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "picotool load --update --verify --execute -t elf"

[build]
target = "thumbv8m.main-none-eabihf"
target-dir = "../target"

[profile.release]
lto = true
